# Site settings
title: Yash Datta
email: saucam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Collection of discoveries and lessons learnt. Hope this saves time and effort 
  of others facing similar problems/issues.
baseurl: /blog # the subpath of your site, e.g. /blog/
url: "http://saucam.github.io" # the base hostname & protocol for your site
twitter_username: ydatta
github_username:  saucam

permalink: '/blog/:year/:month/:day/:title/'
paginate_path: '/blog/page:num/'

# maintain a separate pages folder for markdown files
include: ['_pages']
relative_permalinks: false

# pagination for displaying min number of posts
paginate:      10
paginate_path: '/blog/page:num/'

# Build settings
markdown: kramdown

highlighter: pygments
